### ISSUE TITLE
Long URL results in "Payload Too Large"

### ISSUE THREAD

**Issue by axsddlr** [goniszewski/grimoire-web-extension#3]
This might be in companion to the grimoire container however:

```
SvelteKitError: Content-length of 694059 exceeds limit of 524288 bytes.
    at Object.start (file:///app/build/handler.js:984:19)
    at setupReadableStreamDefaultController (node:internal/webstreams/readablestream:2437:23)
    at setupReadableStreamDefaultControllerFromSource (node:internal/webstreams/readablestream:2470:3)
    at new ReadableStream (node:internal/webstreams/readablestream:290:7)
    at get_raw_body (file:///app/build/handler.js:973:9)
    at getRequest (file:///app/build/handler.js:1052:7)
    at Array.ssr (file:///app/build/handler.js:1230:19)
    at handle (file:///app/build/handler.js:1300:23)
    at file:///app/build/handler.js:1300:40
    at Array.<anonymous> (file:///app/build/handler.js:1219:4) {
  status: 413,
  text: 'Payload Too Large'
}
```
Reproduce:
1. load up: https://www.homedepot.com/p/CyberPower-500VA-120-Volt-6-Outlet-Rackmount-UPS-OR500LCDRM1U/311903186
2. Initiate grimoire companion
3. Try to add bookmark

**Comment by goniszewski** [comment]
Hello @axsddlr! Thank you for reporting it. Although, I have tested this extension with a considerable list of URL's, there's always some possibility I didn't catch every edge-case.

I will look into it!

**Comment by axsddlr** [comment]
> Hello @axsddlr! Thank you for reporting it. Although, I have tested this extension with a considerable list of URL's, there's always some possibility I didn't catch every edge-case.
> 
> It appears that the HTML content fetched from the browser is too big for the default limit. I will look how to handle it properly!

To be fair, adding it manually in grimoire is fine. Thats why I suspect its specific to the extension.

**Comment by goniszewski** [comment]
From what I can find, the default value for `BODY_SIZE_LIMIT` of SvelteKit is to blame (only 512kb, [source](https://kit.svelte.dev/docs/adapter-node#environment-variables-bodysizelimit)).

Because Grimoire loads all `.env` variables during start, you should be able to resolve this issue by adding `BODY_SIZE_LIMIT=5000000` to it.

**Comment by axsddlr** [comment]
@goniszewski that worked!
